# build bin container
FROM docker.io/golang:1.23 as build

WORKDIR /app

COPY ./ ./

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./server cmd/server/*.go

# build container
FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY ./schema/postgres ./schema/postgres/

COPY --from=0 /app/server ./
CMD ["./server"]