version: '3.8'

services:
  postgres_db:
    image: postgres
    container_name: phonebook-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8001:5432"

  app:
    build: .
    container_name: phonebook-app
    restart: unless-stopped
    ports:
      - "8002:8080"
    depends_on:
      - postgres_db